homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('experience/', views.experience, name='experience'),
    path('projects/', views.projects, name='projects'),
    path('skills/', views.skills, name='skills'),
    # path('todoList/', views.todoList, name='todoList'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('todoList/', include('todoList.urls'))
]

todoList/urls.py
from django.urls import path
from . import views

appname = 'todoList'

urlpatterns = [
    path('', views.index, name='todo'),
    path('delete/(?P<delete_id>{0-9})', views.delete, name='delete'),
    path('create/', views.create, name='create'),
]

homepage/models.py
from django.db import models

# Create your models here.

todoList/models.py
from django.db import models
from datetime import *
# Create your models here.
class Post(models.Model):
    nama        = models.CharField(max_length = 20)
    hari        = models.CharField(max_length = 10)
    tempat      = models.CharField(max_length = 20)
    kategori    = models.CharField(max_length = 20)
    tanggal     = models.DateTimeField(default = datetime.now)
    jam         = models.TimeField(max_length = 20)

    def __str__(self):
        return "{}.{}".format(self.nama, self.hari)

homepage/views.py
from django.shortcuts import render
from todoList.views import index as todoList_index

def index(request):
    return render(request, 'index.html')
def experience(request):
    return render(request, 'experience.html')
def projects(request):
    return render(request, 'projects.html')
def skills(request):
    return render(request, 'skills.html')
# def todoList(request):
    # return todoList(request)
# Create your views here.

todoList/views.py
from django.shortcuts import render, redirect
from .todoForm import TodoForm
from .models import Post

def delete(request, delete_id):
    Post.objects.filter(id=delete_id).delete()
    return redirect('todo')

def index(request):
    posts = Post.objects.all()
    context = {
        'posts' : posts,
    }

    return render(request, 'todo.html', context)

def create(request):
    todo_form = TodoForm(request.POST or None)
    if request.method == 'POST':
        if todo_form.is_valid():
            todo_form.save()

            return redirect('todo')

    context = {
        'todo_form' : todo_form
    }

    return render(request,'create.html',context)

homepage/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>
<body data-spy="scroll" data-target="#navbar">
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top ">
        <a href="#" class="navbar-brand"><img src="{% static 'images/logo.png' %}" alt="" id=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{% url 'homepage:index' %}"class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'homepage:experience' %}" class="nav-link">Experience</a>
                </li>   
                <li class="nav-item">
                    <a href="{% url 'homepage:projects' %}"class="nav-link">Projects</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'homepage:skills' %}" class="nav-link">Skills</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'todo' %}" class="nav-link">ToDo</a>
                </li>
            </ul>
        </div>
    </nav>
    
    {% block content %}
    
    {% endblock content %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

homepage/templates/experience.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    Experience
{% endblock title %}

{% block content %}
<div id="experience">
    <div class="head-page">
        <h1>EXPERIENCE</h1>
    </div>
    <div class="content">
        <div class="albayan">
            <div class="logo">
                <img src="{% static 'images/albayan.png' %}" alt="" id="albayan-logo">
            </div>
            <div class="text">
                <h4 id="albayan-text">Al Bayan Senior Highschool</h4>
                <p>Highschool Graduate</p>
                <p>2015 - 2018</p>    
            </div>
        </div>
        <div class="ui">
            <div class="logo">
                <img src="{% static 'images/ui.png' %}" alt="" id="ui-logo">
            </div>
            <div class="text">
                <h4 id="ui-text">Universitas Indonesia</h4>
                <p>Computer Science Undergraduate</p>
                <p>July 2018 - Now</p>
            </div>
        </div>
        <div class="compfest">
            <div class="logo">
                <img src="{% static 'images/compfest.png' %}" alt="" id="compfest-logo">
            </div>
            <div class="text">
                <h4 id="compfest-text">Compfest11</h4>
                <p>Staf of Software Engginering</p>
                <p>March 2019 - Now</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

homepage/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    HomePage
{% endblock title %}

{% block content %}
<div id="home">
    <div class="background">
        <div class="caption text-center">
            <h3>Hello, i am</h3>                  <h1>Muhammad Ilham Alghifari</h1>
            <h4>Extraordinary person with high interest in changing the world to a better place</h4>
        </div>
    </div>
</div>
<div id="about">
    <div class="head-page">
        <h1>ABOUT</h1>
    </div> 
    <div class="content">
        <div class="biopicbox">
            <img src="{% static 'images/biopic.jpg' %}" alt="" id="biopic">
        </div>
        <div class="bio-text">
            <p>About Ilham,</p>
            <p>I am a UI Computer Science student that live in incredible place called Kutek.</p>
            <p>At the moment, i am currently interested in software engineering stuff, so right now im studying fullstack engginer.</p>
        </div>
    </div>
    <div class="sosmed">
        <div class="sosmedbox">
            <a href="#">
                <img src="{% static 'images/twitter.png' %}" alt="" id="twitter">
            </a>
        </div>
            <div class="sosmedbox">
            <a href="#">
                <img src="{% static 'images/linked.png' %}" alt="" id="linked">
            </a>
        </div>
        <div class="sosmedbox">
            <a href="#">
                <img src="{% static 'images/ig.jpg' %}" alt="" id="ig">
            </a>
        </div>
        <div class="sosmedbox">
            <a href="#">
                <img src="{% static 'images/git.png' %}" alt="" id="git">
            </a>
        </div>
    </div>
    <div class="feedback">
        <div class="head-page">
            <h1>Feedback</h1>
        </div> 
        <div class="namaslot">
            Name:<br><input type="text" name="realname"></br>
        </div>
        <div class="emailslot">
            Email:<br><input type="text" name="email"></br>
        </div>
        <div class="comment">
            Comment:<br><textarea name="textarea" rows="15" cols="50"></textarea>
        </div>
    </div>
</div>
{% endblock content %}

homepage/templates/projects.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    Projects
{% endblock title %}

{% block content %}
<div id="projects">
    <div class="head-page">
        <h1>PROJECT</h1>
    </div>
    <div class="content">
        <div class="trangkot">
            <div class="text">
                <h4 id="albayan-text">Trangkot</h4>
                <p>A mobile application that help people to find or rent a public transportion like angkot or bus.
                </p>

                <p>This project purpose is to compete at FMIPA Business Plan Competition.</p>
            </div>
            <div class="logo">
                <img src="{% static 'images/trangkot.png' %}" alt="" id="albayan-logo">
            </div>
        </div>
        <div class="twist2048">
            <div class="text">
                <h4 id="ui-text">2048 with a twist</h4>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minus recusandae ipsa consequuntur ratione ipsum ea impedit obcaecati </p>
            </div>
            <div class="logo">
                <img src="{% static 'images/2048.png' %}" alt="" id="ui-logo">
            </div>
        </div>
    </div>
</div>
{% endblock content %}

homepage/templates/skills.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    Skills
{% endblock title %}

{% block content %}
<div id="skills">
    <div class="head-page">
        <h1>SKILLS</h1>
    </div>
    <div class="toprow">
        <div class="skill-logo">
            <img src="{% static 'images/java.png' %}" alt="" id="java-logo">
        </div>
        <div class="skill-logo">
            <img src="{% static 'images/html.png' %}" alt="" id="html-logo">
        </div>
        <div class="skill-logo">
            <img src="{% static 'images/css.png' %}" alt="" id="css-logo">
        </div>
    </div>
    <div class="botrow">
        <div class="skill-logo">
            <img src="{% static 'images/python.png' %}" alt="" id="python-logo">
        </div>  
        <div class="skill-logo">
            <img src="{% static 'images/pascal.jpg' %}" alt="" id="pascal-logo">
        </div>  
    </div>
</div>
{% endblock content %}

todoList/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>
<body data-spy="scroll" data-target="#navbar">
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top ">
        <a href="#" class="navbar-brand"><img src="{% static 'images/logo.png' %}" alt="" id=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{% url 'homepage:index' %}"class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'homepage:experience' %}" class="nav-link">Experience</a>
                </li>   
                <li class="nav-item">
                    <a href="{% url 'homepage:projects' %}"class="nav-link">Projects</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'homepage:skills' %}" class="nav-link">Skills</a>
                </li>
                <li class="nav-item">
                    <a href="#about" class="nav-link">About</a>
                </li>
            </ul>
        </div>
    </nav>
    
    {% block content %}
    
    {% endblock content %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

todoList/templates/create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    Create TodoList
{% endblock title %}

{% block content %}
<h1>Lorem ipsum dolor sit, amet </h1>


<body>
    <form method='POST'>
        {% csrf_token %}
        <!-- <table>
            {{todo_form.as_table}}
        </table> -->
        {% for form in todo_form %}
			<div class="form-group col-md-6">
				{{form.label}}
				{{form}}
			</div>
		{% endfor %}
        <button type = "Submit" class="btn btn-secondary">Submit</button>
        <!-- <a href="{% url 'create' %}" class="btn btn-secondary">Tambah</a> -->
    </form>
</body>
{% endblock content %}

todoList/templates/todo.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    TodoList
{% endblock title %}

{% block content %}
<h1>Lorem ipsum dolor sit, amet </h1>
<body>
    <!-- {% for post in posts %}
		<h4>{{post.nama}}</h4>
		<h4>{{post.hari}}</h4>
		<h4>{{post.tempat}}</h4>
		<h4>{{post.kategori}}</h4>
		<h4>{{post.tanggal}}</h4>
		<h4>{{post.jam}}</h4>
	{% endfor %} -->
	<table class="table table-dark">
		<thead>
		  	<tr>
				<th scope="col">#</th>
				<th scope="col">Kegiatan</th>
				<th scope="col">Hari</th>
				<th scope="col">Tempat</th>
				<th scope="col">Kategori</th>
				<th scope="col">Tanggal</th>
				<th scope="col">Jam</th>
				<!-- <th scope="col">Done</th> -->
			</tr>
		</thead>
		<tbody>
			{% for post in posts %}
				<tr>
					<th scope="row">{{forloop.counter}}</th>
					<td>{{post.nama}}</td>
					<td>{{post.hari}}</td>
					<td>{{post.tempat}}</td>
					<td>{{post.kategori}}</td>
					<td>{{post.tanggal}}</td>			<td>{{post.jam}}</td>
					<td>
						<a href="{% url 'delete' post.id %}" class="btn btn-light">Done</a>			
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	<a href="{% url 'create' %}" class="btn btn-secondary">Tambah</a>
</body>
{% endblock content %}